name: Hello World
author: Alberto Vázquez
dscription: Hello world action inside docker
inputs:
  who-to-greet:
    description: Who to great
    required: true
    default: Beto
outputs:
  time:
    description: Time of run
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.who-to-greet }}

