name: Send slack message
author: Alberto Vázquez
dscription: Send to slack workflow information
inputs:
  slack_webhook:
    description: Slack webhook url
    required: true
  message:
    description: Slack message
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.slack_webhook }}
    - ${{ inputs.message }}

