name: Testing custom actions
on: push

jobs:
  testing-hello-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello
        id: hello
        with:
          who-to-greet: World
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: TITLE
          body: Body
          assignees: |
            icyd
            amalivaca
      - run: |
          echo "Time: ${{ steps.issue.outputs.issue }}"
